{% set version = "3.1.7" %}

package:
  name: terminaltables
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/t/terminaltables/terminaltables-{{ version }}.tar.gz
    sha256: 5dab2f33927c0a020b8011c81b92830ff9fd4ba701657da5d7bfdc41048360a6
  - url: https://raw.githubusercontent.com/matthewdeanmartin/terminaltables/master/LICENSE
    sha256: 2e1320fd337db06a3136d0f4101bd62f13249c95c5b581304f35481e979d432a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=2.7
  run:
    - colorama
    - python >=2.7
    - termcolor

test:
  requires:
    - pip
    - m2-grep  # [win]
  imports:
    - terminaltables
  commands:
    - pip check
    - pip list
    - pip list | grep -E "terminaltables\s+{{ version.replace(".", "\\.") }}"

about:
  home: https://github.com/matthewdeanmartin/terminaltables
  license: MIT
  license_family: MIT
  # xref : https://github.com/Robpol86/terminaltables/pull/49
  license_file: LICENSE
  summary: Generate simple tables in terminals from a nested list of strings.

extra:
  recipe-maintainers:
    - mariusvniekerk
    - bollwyvl
